version: '3.7'

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    image: php:7.4-fpm
    volumes:
      - ./index.php:/var/www/html/index.php
    depends_on:
      - db

  web:
    image: nginx:alpine
    volumes:
      - ./index.php:/usr/share/nginx/html/index.php
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - backend
